version: '3.8'

services:
  weaviate-ui:
     image: naaive/weaviate-ui:latest
     environment:
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_API_KEYS=secret
     ports:
       - "7777:7777"
     depends_on:
       - weaviate

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.8
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
  vllm-deepseek:
    image: vllm/vllm-openai:latest
    container_name: vllm-deepseek-coder
    runtime: nvidia
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - /tmp:/tmp
    command: [
      "--model", "deepseek-ai/deepseek-coder-1.3b-instruct",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--served-model-name", "deepseek-coder-1.3b-instruct",
      "--max-model-len", "4096",
      "--gpu-memory-utilization", "0.90",
      "--dtype", "half",
      "--max-num-seqs", "8",
      "--tensor-parallel-size", "1",
      "--pipeline-parallel-size", "1",
      "--block-size", "16",
      "--disable-log-stats",
      "--trust-remote-code",
      "--max-num-batched-tokens", "2048"
    ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
  weaviate_data:

networks:
  default:
    name: vllm-network